import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { CalendarSideBar } from "@/components/custom/CalendarSideBar";
import { AuthProvider } from "@/components/AuthProvider";
import { CalendarProvider } from "@/components/CalendarContext";
import { AuthButton } from "@/components/AuthButton";

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendDeca.variable} antialiased`}
      >
        <AuthProvider>
          <CalendarProvider>
            <SidebarProvider defaultOpen={false}>
              <CalendarSideBar />
              <main className="w-full relative">
                <div className="fixed top-4 right-4 z-50">
                  <AuthButton />
                </div>
                {children}
              </main>
            </SidebarProvider>
          </CalendarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
